# Generated by Django 6.1.1 on 2026-09-16 12:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('upload', 'File upload'), ('aircasting', 'AirCasting sync'), ('cli', 'Command line'), ('demo', 'Demo data')], max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('complete', 'Complete'), ('partial', 'Complete with warnings'), ('failed', 'Failed')], default='running', max_length=16)),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('started_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('rows_read', models.PositiveBigIntegerField(default=0)),
                ('rows_stored', models.PositiveBigIntegerField(default=0)),
                ('rows_duplicate', models.PositiveBigIntegerField(default=0)),
                ('rows_rejected', models.PositiveBigIntegerField(default=0)),
                ('stations', models.JSONField(blank=True, default=list)),
                ('message', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('interval_minutes', models.PositiveIntegerField(default=15)),
                ('last_run', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('region', models.CharField(blank=True, default='Ireland', max_length=80)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('location_source', models.CharField(choices=[('fixed_session', 'Fixed session coordinates'), ('measurement_median', 'Median of mobile readings'), ('file', 'Coordinates in imported file'), ('manual', 'Entered manually'), ('none', 'No location yet')], default='none', max_length=24)),
                ('is_indoor', models.BooleanField(default=False)),
                ('first_reading', models.DateTimeField(blank=True, null=True)),
                ('last_reading', models.DateTimeField(blank=True, null=True)),
                ('reading_count', models.PositiveBigIntegerField(default=0)),
                ('measurements', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='observatory.station')),
            ],
        ),
        migrations.CreateModel(
            name='AirCastingDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(help_text='As written on the label, e.g. AIRBEAM3:B0B21C7627C4', max_length=64, unique=True)),
                ('label', models.CharField(blank=True, max_length=120)),
                ('known_session_ids', models.CharField(blank=True, help_text='Comma-separated session numbers from map links', max_length=255)),
                ('project_tags', models.CharField(blank=True, help_text='Comma-separated authorised project tags', max_length=255)),
                ('download_from', models.DateField(default='2020-01-01')),
                ('active', models.BooleanField(default=True)),
                ('last_success', models.DateTimeField(blank=True, null=True)),
                ('station', models.ForeignKey(blank=True, help_text="Optional: store this device's readings under an existing station", null=True, on_delete=django.db.models.deletion.SET_NULL, to='observatory.station')),
            ],
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('period_end', models.DateField()),
                ('filename', models.CharField(max_length=255)),
                ('readings', models.PositiveBigIntegerField(default=0)),
                ('measurements', models.JSONField(blank=True, default=list)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='observatory.station')),
            ],
            options={
                'ordering': ['-period_start', 'station__name'],
                'constraints': [models.UniqueConstraint(fields=('station', 'period_start'), name='one_dataset_per_station_week')],
            },
        ),
    ]
