# Generated by Django 5.2.16 on 2026-09-16 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='importrun',
            name='rows_deleted',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='importrun',
            name='source',
            field=models.CharField(choices=[('upload', 'File upload'), ('aircasting', 'AirCasting sync'), ('cli', 'Command line'), ('demo', 'Demo data'), ('deletion', 'Deletion')], max_length=16),
        ),
    ]
