# Generated by Django 5.2.16 on 2026-09-16 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0002_importrun_rows_deleted_alter_importrun_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='aircastingdevice',
            name='download_until',
            field=models.DateField(blank=True, help_text='Leave empty to keep downloading up to now', null=True),
        ),
        migrations.AddField(
            model_name='aircastingdevice',
            name='last_attempt',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aircastingdevice',
            name='last_error',
            field=models.TextField(blank=True, help_text='Why the most recent download failed; cleared on success'),
        ),
        migrations.AlterField(
            model_name='aircastingdevice',
            name='download_from',
            field=models.DateField(default='2020-01-01', help_text='Download recordings made from this date onwards'),
        ),
    ]
