# Generated by Django 5.2.16 on 2026-09-16 21:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0003_aircastingdevice_download_until_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircastingdevice',
            name='download_from',
            field=models.DateField(default=datetime.date(2020, 1, 1), help_text='Download recordings made from this date onwards'),
        ),
    ]
