# Generated by Django 5.2.16 on 2026-09-17 12:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0004_alter_aircastingdevice_download_from'),
    ]

    operations = [
        migrations.CreateModel(
            name='SurveyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('created_on', models.DateField(default=django.utils.timezone.localdate)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='SurveyResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_version', models.CharField(default='1.0', max_length=8)),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('consent_given', models.BooleanField()),
                ('age_confirmed', models.BooleanField()),
                ('consent_text_version', models.CharField(default='1.0', max_length=8)),
                ('county', models.CharField(max_length=32)),
                ('area_type', models.CharField(max_length=32)),
                ('near_border', models.BooleanField(default=False)),
                ('air_quality_rating', models.CharField(max_length=32)),
                ('pollution_sources', models.JSONField(blank=True, default=list)),
                ('dashboard_usefulness', models.CharField(max_length=32)),
                ('dashboard_improvements', models.JSONField(blank=True, default=list)),
                ('dashboard_improvements_other', models.CharField(blank=True, max_length=120)),
                ('sensor_trust', models.CharField(max_length=32)),
                ('trust_concerns', models.JSONField(blank=True, default=list)),
                ('participation', models.JSONField(blank=True, default=list)),
                ('open_data_support', models.CharField(max_length=32)),
                ('additional_comments', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
