# Generated by Django 5.2.16 on 2026-09-17 12:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observatory', '0005_surveycontact_surveyresponse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='surveycontact',
            name='created_on',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
